name: Update Weather Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-weather:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install packages
        run: |
          pip install -r requirements.txt


      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GC_SERVICE_KEY_CREDENTIALS }}
          create_credentials_file: true
          export_environment_variables: true


      - name: Upload weather
        run: |
          python update_weather.py
