name: Update Weather Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # Run every hour (UTC)

jobs:
  update-weather:

    runs-on: ubuntu-latest

    steps:

      # Get repository code
      - name: Checkout
        uses: actions/checkout@v4


      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # Install Python packages
      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      # Create Google service account JSON file
      - name: Create Google credentials file
        run: |
          echo '${{ secrets.GC_SERVICE_KEY_CREDENTIALS }}' > key.json

      - name: Check credentials file
        run: |
          ls -la
          echo "Checking key.json..."
          head -5 key.json


      # Run weather uploader
      - name: Upload weather data
        run: |
          python update_weather.py